application: zandbergenmediation
version: 1
runtime: go
api_version: go1

default_expiration: "365d"

handlers:
- url: /html
  static_dir: html

- url: /css
  static_dir: html/css

- url: /img
  static_dir: html/img
  # expiration: "1d"

- url: /static
  static_dir: html/static

- url: /.*
  script: _go_app

